CREATE DATABASE IF NOT EXISTS SILVER;
USE DATABASE SILVER;

CREATE SCHEMA IF NOT EXISTS FINANCE;
CREATE SCHEMA IF NOT EXISTS UTILS;

USE SCHEMA FINANCE;

-- ================================
-- TABLE DEFINITIONS
-- ================================
-- Audit_Job_Log table
create or replace TABLE SILVER.FINANCE.AUDIT_JOB_LOG (
	JOB_ID VARCHAR(255),
	JOB_NAME VARCHAR(255),
	LAYER_NAME VARCHAR(255),
	SOURCE_OBJECT VARCHAR(255),
	TARGET_OBJECT VARCHAR(255),
	START_TIME TIMESTAMP_NTZ(9),
	END_TIME TIMESTAMP_NTZ(9),
	ROWS_PROCESSED NUMBER(38,0),
	ROWS_INSERTED NUMBER(38,0),
	ROWS_UPDATED NUMBER(38,0),
	ROWS_FAILED NUMBER(38,0),
	JOB_STATUS VARCHAR(255),
	ERROR_MESSAGE VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Customers Table
CREATE OR REPLACE TABLE SILVER.FINANCE.CUSTOMERS (
    CUSTOMER_SK NUMBER AUTOINCREMENT,
    CUSTOMER_ID VARCHAR(255),
    CUSTOMER_TYPE VARCHAR(100),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    ORGANIZATION_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(50),
    TAX_IDENTIFIER VARCHAR(50),
    RISK_PROFILE VARCHAR(50),
    KYC_STATUS VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    RECORD_HASH VARCHAR(255),
    AUDIT_JOB_ID VARCHAR(255),
    DQ_STATUS VARCHAR(50),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Rejected Customers Table
CREATE OR REPLACE TABLE SILVER.FINANCE.CUSTOMERS_REJECTED (
    CUSTOMER_ID VARCHAR,
    EMAIL VARCHAR,
    PHONE_NUMBER VARCHAR,
    TAX_IDENTIFIER VARCHAR,
    AUDIT_JOB_ID VARCHAR,
    REJECTION_REASON VARCHAR,
    REJECTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Accounts table
create or replace TABLE SILVER.FINANCE.ACCOUNTS (
	ACCOUNT_ID VARCHAR(255),
	CUSTOMER_ID VARCHAR(255),
	ACCOUNT_NUMBER VARCHAR(255),
	ACCOUNT_TYPE VARCHAR(255),
	ACCOUNT_STATUS VARCHAR(255),
	BASE_CURRENCY VARCHAR(255),
	OPENED_DATE DATE,
	CLOSED_DATE DATE,
	ADVISOR_CODE VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9), 	
	RECORD_HASH VARCHAR(255),
	AUDIT_JOB_ID VARCHAR(255),
	DQ_STATUS VARCHAR(50),
	LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
-- Rejected Accounts table
create or replace TABLE SILVER.FINANCE.ACCOUNTS_REJECTED (
    ACCOUNT_ID VARCHAR(255),
    CUSTOMER_ID VARCHAR(255),
    ACCOUNT_NUMBER VARCHAR(255),
    ACCOUNT_TYPE VARCHAR(255),
    ACCOUNT_STATUS VARCHAR(255),
    BASE_CURRENCY VARCHAR(255),
    OPENED_DATE DATE,
    CLOSED_DATE DATE,
    ADVISOR_CODE VARCHAR(255),
    AUDIT_JOB_ID VARCHAR(255),
    REJECTION_REASON VARCHAR(1000),
    REJECTED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Cash_Transactions table
create or replace TABLE SILVER.FINANCE.CASH_TRANSACTIONS (
	CASH_TRANSACTION_ID VARCHAR(255),
	ACCOUNT_ID VARCHAR(255),
	TRANSACTION_DATE TIMESTAMP_NTZ(9),
	TRANSACTION_TYPE VARCHAR(255),
	AMOUNT NUMBER(18,4),
	CURRENCY VARCHAR(255),
	REFERENCE_NUMBER VARCHAR(255),
	TRANSACTION_STATUS VARCHAR(255),
	FEE_AMOUNT NUMBER(18,4),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	RECORD_HASH VARCHAR(255),
	AUDIT_JOB_ID VARCHAR(255),
	DQ_STATUS VARCHAR(50),
	LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
-- Rejected Cash_Transactions table
CREATE OR REPLACE TABLE SILVER.FINANCE.CASH_TRANSACTIONS_REJECTED (
    CASH_TRANSACTION_ID VARCHAR(255),
    ACCOUNT_ID VARCHAR(255),
    TRANSACTION_DATE TIMESTAMP_NTZ(9),
    TRANSACTION_TYPE VARCHAR(255),
    AMOUNT NUMBER(18,4),
    CURRENCY VARCHAR(255),
    REFERENCE_NUMBER VARCHAR(255),
    TRANSACTION_STATUS VARCHAR(255),
    FEE_AMOUNT NUMBER(18,4),
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    AUDIT_JOB_ID VARCHAR(255),
    REJECTION_REASON VARCHAR(1000),
    REJECTED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Market_Prices Table
create or replace TABLE SILVER.FINANCE.MARKET_PRICES (
	PRICE_ID VARCHAR(255),
	SECURITY_ID VARCHAR(255),
	PRICE_DATE DATE,
	OPEN_PRICE NUMBER(18,6),
	HIGH_PRICE NUMBER(18,6),
	LOW_PRICE NUMBER(18,6),
	CLOSE_PRICE NUMBER(18,6),
	ADJUSTED_CLOSE_PRICE NUMBER(18,6),
	PRICE_CURRENCY VARCHAR(255),
	FX_RATE_TO_BASE NUMBER(18,8),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	RECORD_HASH VARCHAR(255),
	AUDIT_JOB_ID VARCHAR(255),
	DQ_STATUS VARCHAR(50),
	LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
-- Rejected Market_Prices table
CREATE OR REPLACE TABLE SILVER.FINANCE.MARKET_PRICES_REJECTED (
    PRICE_ID VARCHAR(255),
    SECURITY_ID VARCHAR(255),
    PRICE_DATE DATE,
    OPEN_PRICE NUMBER(18,6),
    HIGH_PRICE NUMBER(18,6),
    LOW_PRICE NUMBER(18,6),
    CLOSE_PRICE NUMBER(18,6),
    ADJUSTED_CLOSE_PRICE NUMBER(18,6),
    PRICE_CURRENCY VARCHAR(255),
    FX_RATE_TO_BASE NUMBER(18,8),
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    AUDIT_JOB_ID VARCHAR(255),
    REJECTION_REASON VARCHAR(1000),
    REJECTED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Securities table
create or replace TABLE SILVER.FINANCE.SECURITIES (
	SECURITY_ID VARCHAR(255),
	SECURITY_SYMBOL VARCHAR(255),
	SECURITY_NAME VARCHAR(255),
	ISIN_CODE VARCHAR(255),
	SECURITY_TYPE VARCHAR(255),
	ASSET_CLASS VARCHAR(255),
	EXCHANGE_CODE VARCHAR(255),
	CURRENCY VARCHAR(255),
	FACE_VALUE NUMBER(18,4),
	COUPON_RATE NUMBER(10,4),
	MATURITY_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	RECORD_HASH VARCHAR(255),
	AUDIT_JOB_ID VARCHAR(255),
	DQ_STATUS VARCHAR(50),
	LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
-- Rejected Securities table
CREATE OR REPLACE TABLE SILVER.FINANCE.SECURITIES_REJECTED (
    SECURITY_ID VARCHAR(255),
    SECURITY_SYMBOL VARCHAR(255),
    SECURITY_NAME VARCHAR(255),
    ISIN_CODE VARCHAR(255),
    SECURITY_TYPE VARCHAR(255),
    ASSET_CLASS VARCHAR(255),
    EXCHANGE_CODE VARCHAR(255),
    CURRENCY VARCHAR(255),
    FACE_VALUE NUMBER(18,4),
    COUPON_RATE NUMBER(10,4),
    MATURITY_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    AUDIT_JOB_ID VARCHAR(255),
    REJECTION_REASON VARCHAR(1000),
    REJECTED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Trades Table
create or replace TABLE SILVER.FINANCE.TRADES (
	TRADE_ID VARCHAR(255),
	ACCOUNT_ID VARCHAR(255),
	SECURITY_ID VARCHAR(255),
	TRADE_DATE TIMESTAMP_NTZ(9),
	SETTLEMENT_DATE DATE,
	TRADE_TYPE VARCHAR(255),
	QUANTITY NUMBER(18,4),
	TRADE_PRICE NUMBER(18,6),
	BROKERAGE_RATE NUMBER(10,6),
	TAX_RATE NUMBER(10,6),
	EXCHANGE_FEE NUMBER(18,4),
	TRADE_CURRENCY VARCHAR(255),
	TRADE_STATUS VARCHAR(255),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	RECORD_HASH VARCHAR(255),
	AUDIT_JOB_ID VARCHAR(255),
	DQ_STATUS VARCHAR(50),
	LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
-- Rejected Trades table
CREATE OR REPLACE TABLE SILVER.FINANCE.TRADES_REJECTED (
    TRADE_ID VARCHAR(255),
    ACCOUNT_ID VARCHAR(255),
    SECURITY_ID VARCHAR(255),
    TRADE_DATE TIMESTAMP_NTZ(9),
    SETTLEMENT_DATE DATE,
    TRADE_TYPE VARCHAR(255),
    QUANTITY NUMBER(18,4),
    TRADE_PRICE NUMBER(18,6),
    BROKERAGE_RATE NUMBER(10,6),
    TAX_RATE NUMBER(10,6),
    EXCHANGE_FEE NUMBER(18,4),
    TRADE_CURRENCY VARCHAR(255),
    TRADE_STATUS VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    AUDIT_JOB_ID VARCHAR(255),
	REJECTION_REASON VARCHAR(1000),
    REJECTED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =========
-- STREAMS
-- =========
CREATE OR REPLACE STREAM SILVER.FINANCE.STR_Silver_Customers 
ON TABLE SILVER.FINANCE.CUSTOMERS;

CREATE OR REPLACE STREAM SILVER.FINANCE.STR_Silver_Accounts 
ON TABLE SILVER.FINANCE.ACCOUNTS;

CREATE OR REPLACE STREAM SILVER.FINANCE.STR_Silver_CashTransactions 
ON TABLE SILVER.FINANCE.CASH_TRANSACTIONS;

CREATE OR REPLACE STREAM SILVER.FINANCE.STR_Silver_MarketPrices 
ON TABLE SILVER.FINANCE.MARKET_PRICES;

CREATE OR REPLACE STREAM SILVER.FINANCE.STR_Silver_Securities 
ON TABLE SILVER.FINANCE.SECURITIES;

CREATE OR REPLACE STREAM SILVER.FINANCE.STR_Silver_Trades 
ON TABLE SILVER.FINANCE.TRADES;

