CREATE OR REPLACE PROCEDURE TASKS_DB.TASKS_SCHEMA.SP_MANAGE_TASKS(
    P_ACTION STRING   -- RESUME / SUSPEND
)
RETURNS STRING
LANGUAGE SQL
AS
$$

DECLARE

    V_ACTION STRING;

BEGIN

    V_ACTION := UPPER(P_ACTION);

    IF (V_ACTION NOT IN ('RESUME','SUSPEND')) THEN
        RETURN 'INVALID ACTION. USE RESUME OR SUSPEND';
    END IF;

    -- RESUME TASKS: Parent task should be resumed LAST 
    
    IF (V_ACTION = 'RESUME') THEN

        -- FACT TASKS
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_CASH_TRANSACTION_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_TRADE_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_PORTFOLIO_POSITION_LOAD RESUME';
        
        -- DIM TASKS
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_CUSTOMER_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_ACCOUNT_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_SECURITY_LOAD RESUME';
        
        -- SILVER TASKS
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD RESUME';
        
        -- BRONZE TASKS
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CUSTOMERS_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ACCOUNTS_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CASH_TRANSACTIONS_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_MARKET_PRICES_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_SECURITIES_LOAD RESUME';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_TRADES_LOAD RESUME';

        -- ROOT TASK LAST
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER RESUME';
        
        RETURN 'ALL TASKS RESUMED SUCCESSFULLY';

    END IF;

    -- SUSPEND TASKS: Parent task should be suspended FIRST

    IF (V_ACTION = 'SUSPEND') THEN

        -- ROOT TASKS FIRST
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER SUSPEND';
         
        -- BRONZE TASKS
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CUSTOMERS_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ACCOUNTS_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CASH_TRANSACTIONS_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_MARKET_PRICES_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_SECURITIES_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_TRADES_LOAD SUSPEND';
        
        -- SILVER TASKS
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD SUSPEND';
        
        -- DIM TASKS
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_CUSTOMER_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_ACCOUNT_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_SECURITY_LOAD SUSPEND';
        
        -- FACT TASKS
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_CASH_TRANSACTION_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_TRADE_LOAD SUSPEND';
        EXECUTE IMMEDIATE 'ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_PORTFOLIO_POSITION_LOAD SUSPEND';

        RETURN 'ALL TASKS SUSPENDED SUCCESSFULLY';

    END IF;

END;

$$;