-- CREATE DATABASE IF NOT EXISTS TASKS_DB;
-- USE DATABASE TASKS_DB;

-- CREATE SCHEMA IF NOT EXISTS TASKS_SCHEMA;
-- USE SCHEMA TASKS_SCHEMA;

-- -- ==============
-- -- brone task
-- -- ==============

-- CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.BRONZE_TASK
-- WAREHOUSE = COMPUTE_WH
-- SCHEDULE = '2 MINUTE'
-- WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.STR_BRONZE_STAGE')
-- AS
-- BEGIN
--     CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('CUSTOMERS');
--     CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('ACCOUNTS');
--     CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('CASH_TRANSACTIONS');
--     CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('MARKET_PRICES');
--     CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('TRADES');
--     CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('SECURITIES');
-- END;


-- -- ================
-- -- silver tasks
-- -- ================
-- -- Task for CUSTOMERS table
-- CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD
-- WAREHOUSE = COMPUTE_WH
-- -- SCHEDULE = '2 MINUTE'
-- AFTER TASKS_DB.TASKS_SCHEMA.BRONZE_TASK
-- WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_CUSTOMERS_STREAM')
-- AS
-- CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
-- (
--     'CUSTOMERS_BRONZE_TO_SILVER',
--     'SILVER',
--     'BRONZE.FINANCE.CUSTOMERS',
--     'SILVER.FINANCE.CUSTOMERS',
--     'SILVER.UTILS.SP_CUSTOMERS_SILVER_TRANSFORMATIONS',
--     'kgirija@defteam.co'
-- );

-- -- Task for ACCOUNTS table
-- CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD
-- WAREHOUSE = COMPUTE_WH
-- -- SCHEDULE = '2 MINUTE'
-- AFTER TASKS_DB.TASKS_SCHEMA.BRONZE_TASK
-- WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_ACCOUNTS_STREAM')
-- AS
-- CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
-- (
--     'ACCOUNTS_BRONZE_TO_SILVER',
--     'SILVER',
--     'BRONZE.FINANCE.ACCOUNTS',
--     'SILVER.FINANCE.ACCOUNTS',
--     'SILVER.UTILS.SP_ACCOUNTS_SILVER_TRANSFORMATIONS',
--     'kgirija@defteam.co'
-- );

-- --  Task for CASH_TRANSACTIONS table
-- CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD
-- WAREHOUSE = COMPUTE_WH
-- -- SCHEDULE = '2 MINUTE'
-- AFTER TASKS_DB.TASKS_SCHEMA.BRONZE_TASK
-- WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_CASHTRANSACTIONS_STREAM')
-- AS
-- CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
-- (
--     'CASH_TRANSACTIONS_BRONZE_TO_SILVER',
--     'SILVER',
--     'BRONZE.FINANCE.CASH_TRANSACTIONS',
--     'SILVER.FINANCE.CASH_TRANSACTIONS',
--     'SILVER.UTILS.SP_CASH_TRANSACTIONS_SILVER_TRANSFORMATIONS',
--     'kgirija@defteam.co'
-- );

-- -- Task for MARKET_PRICES table
-- CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD
-- WAREHOUSE = COMPUTE_WH
-- -- SCHEDULE = '2 MINUTE'
-- AFTER TASKS_DB.TASKS_SCHEMA.BRONZE_TASK
-- WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_MARKETPRICES_STREAM')
-- AS
-- CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
-- (
--     'MARKET_PRICES_BRONZE_TO_SILVER',
--     'SILVER',
--     'BRONZE.FINANCE.MARKET_PRICES',
--     'SILVER.FINANCE.MARKET_PRICES',
--     'SILVER.UTILS.SP_MARKET_PRICES_SILVER_TRANSFORMATIONS',
--     'kgirija@defteam.co'
-- );

-- -- Task for SECURITIES table
-- CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD
-- WAREHOUSE = COMPUTE_WH
-- -- SCHEDULE = '2 MINUTE'
-- AFTER TASKS_DB.TASKS_SCHEMA.BRONZE_TASK
-- WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_SECURITIES_STREAM')
-- AS
-- CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
-- (
--     'SECURITIES_BRONZE_TO_SILVER',
--     'SILVER',
--     'BRONZE.FINANCE.SECURITIES',
--     'SILVER.FINANCE.SECURITIES',
--     'SILVER.UTILS.SP_SECURITIES_SILVER_TRANSFORMATIONS',
--     'kgirija@defteam.co'
-- );

-- -- Task for TRADES table
-- CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD
-- WAREHOUSE = COMPUTE_WH
-- -- SCHEDULE = '2 MINUTE'
-- AFTER TASKS_DB.TASKS_SCHEMA.BRONZE_TASK
-- WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_TRADES_STREAM')
-- AS
-- CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
-- (
--     'TRADES_BRONZE_TO_SILVER',
--     'SILVER',
--     'BRONZE.FINANCE.TRADES',
--     'SILVER.FINANCE.TRADES',
--     'SILVER.UTILS.SP_TRADES_SILVER_TRANSFORMATIONS',
--     'kgirija@defteam.co'
-- );


-- -- ============================
-- -- Resuming/Suspending tasks
-- -- ============================
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.BRONZE_TASK RESUME; -- Root/Parent task

-- ALTER TASK TASKS_DB.TASKS_SCHEMA.BRONZE_TASK SUSPEND;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD SUSPEND;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD SUSPEND;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD SUSPEND;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD SUSPEND;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD SUSPEND;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD SUSPEND;


-- CALL TASKS_DB.TASKS_SCHEMA.SP_MANAGE_TASKS('RESUME');

-- CALL TASKS_DB.TASKS_SCHEMA.SP_MANAGE_TASKS('SUSPEND');

SHOW TASKS;


-- =========================================================
-- ROOT TASK
-- =========================================================
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER
WAREHOUSE = COMPUTE_WH
SCHEDULE = '2 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.STR_BRONZE_STAGE')
AS
SELECT 1;

-- =========================================================
-- BRONZE TASKS
-- =========================================================

-- CUSTOMERS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CUSTOMERS_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER
AS
CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('CUSTOMERS');


-- ACCOUNTS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ACCOUNTS_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER
AS
CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('ACCOUNTS');


-- CASH_TRANSACTIONS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CASH_TRANSACTIONS_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER
AS
CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('CASH_TRANSACTIONS');


-- MARKET_PRICES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_MARKET_PRICES_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER
AS
CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('MARKET_PRICES');


-- SECURITIES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_SECURITIES_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER
AS
CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('SECURITIES');


-- TRADES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_TRADES_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER
AS
CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('TRADES');



-- =========================================================
-- SILVER TASKS
-- =========================================================

-- CUSTOMERS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CUSTOMERS_LOAD
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_CUSTOMERS_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'CUSTOMERS_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.CUSTOMERS',
    'SILVER.FINANCE.CUSTOMERS',
    'SILVER.UTILS.SP_CUSTOMERS_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- ACCOUNTS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ACCOUNTS_LOAD
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_ACCOUNTS_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'ACCOUNTS_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.ACCOUNTS',
    'SILVER.FINANCE.ACCOUNTS',
    'SILVER.UTILS.SP_ACCOUNTS_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- CASH_TRANSACTIONS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CASH_TRANSACTIONS_LOAD
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_CASHTRANSACTIONS_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'CASH_TRANSACTIONS_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.CASH_TRANSACTIONS',
    'SILVER.FINANCE.CASH_TRANSACTIONS',
    'SILVER.UTILS.SP_CASH_TRANSACTIONS_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- MARKET_PRICES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_MARKET_PRICES_LOAD
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_MARKETPRICES_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'MARKET_PRICES_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.MARKET_PRICES',
    'SILVER.FINANCE.MARKET_PRICES',
    'SILVER.UTILS.SP_MARKET_PRICES_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- SECURITIES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_SECURITIES_LOAD
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_SECURITIES_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'SECURITIES_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.SECURITIES',
    'SILVER.FINANCE.SECURITIES',
    'SILVER.UTILS.SP_SECURITIES_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- TRADES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_TRADES_LOAD
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_TRADES_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'TRADES_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.TRADES',
    'SILVER.FINANCE.TRADES',
    'SILVER.UTILS.SP_TRADES_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);



-- =========================================================
-- GOLD DIM TASKS
-- =========================================================

-- DIM_CUSTOMER
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_CUSTOMER_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD
AS
CALL GOLD.UTILS.SP_LOAD_DIM_CUSTOMER();


-- DIM_ACCOUNT
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_ACCOUNT_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD
AS
CALL GOLD.UTILS.SP_LOAD_DIM_ACCOUNT();


-- DIM_SECURITY
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_SECURITY_LOAD
WAREHOUSE = COMPUTE_WH
AFTER TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD
AS
CALL GOLD.UTILS.SP_LOAD_DIM_SECURITY();



-- =========================================================
-- GOLD FACT TASKS
-- =========================================================

-- FACT_CASH_TRANSACTION
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_CASH_TRANSACTION_LOAD
WAREHOUSE = COMPUTE_WH
AFTER
    TASKS_DB.TASKS_SCHEMA.TASK_DIM_CUSTOMER_LOAD,
    TASKS_DB.TASKS_SCHEMA.TASK_DIM_ACCOUNT_LOAD,
    TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD
AS
CALL GOLD.UTILS.SP_LOAD_FACT_CASH_TRANSACTION();


-- FACT_TRADE
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_TRADE_LOAD
WAREHOUSE = COMPUTE_WH
AFTER
    TASKS_DB.TASKS_SCHEMA.TASK_DIM_CUSTOMER_LOAD,
    TASKS_DB.TASKS_SCHEMA.TASK_DIM_ACCOUNT_LOAD,
    TASKS_DB.TASKS_SCHEMA.TASK_DIM_SECURITY_LOAD,
    TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD
AS
CALL GOLD.UTILS.SP_LOAD_FACT_TRADE();


-- FACT_PORTFOLIO_POSITION
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_PORTFOLIO_POSITION_LOAD
WAREHOUSE = COMPUTE_WH
AFTER
    TASKS_DB.TASKS_SCHEMA.TASK_DIM_CUSTOMER_LOAD,
    TASKS_DB.TASKS_SCHEMA.TASK_DIM_ACCOUNT_LOAD,
    TASKS_DB.TASKS_SCHEMA.TASK_DIM_SECURITY_LOAD,
    TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD
AS
CALL GOLD.UTILS.SP_LOAD_FACT_PORTFOLIO_POSITION();



-- =========================================================
-- RESUME TASKS
-- =========================================================

CALL TASKS_DB.TASKS_SCHEMA.SP_MANAGE_TASKS('RESUME');

CALL TASKS_DB.TASKS_SCHEMA.SP_MANAGE_TASKS('SUSPEND');

SHOW TASKS;

-- -- FACT TASKS
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_CASH_TRANSACTION_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_TRADE_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_FACT_PORTFOLIO_POSITION_LOAD RESUME;

-- -- DIM TASKS
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_CUSTOMER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_ACCOUNT_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_DIM_SECURITY_LOAD RESUME;

-- -- SILVER TASKS
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD RESUME;

-- -- BRONZE TASKS (ROOT TASKS LAST)
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CUSTOMERS_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ACCOUNTS_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CASH_TRANSACTIONS_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_MARKET_PRICES_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_SECURITIES_LOAD RESUME;
-- ALTER TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_TRADES_LOAD RESUME;