
-- =========================================================
-- ROOT TASK ( will load data from new file to respective tables )
-- =========================================================
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ROUTER
WAREHOUSE = COMPUTE_WH
-- SCHEDULE = '5 MINUTE'
-- SCHEDULE = 'USING CRON 35 14 * * * Asia/Kolkata' --Every day, min:hour -- 24 hour format
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.STR_BRONZE_STAGE')
AS
CALL BRONZE.UTILS.SP_PROCESS_STAGE_FILES();


-- =========================================================
-- SILVER TASKS
-- =========================================================

-- CUSTOMERS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_CUSTOMERS_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
-- AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CUSTOMERS_LOAD -- Not necessary as we are checking on streams
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_CUSTOMERS_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'CUSTOMERS_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.CUSTOMERS',
    'SILVER.FINANCE.CUSTOMERS',
    'SILVER.UTILS.SP_CUSTOMERS_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- ACCOUNTS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_ACCOUNTS_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
-- AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_ACCOUNTS_LOAD -- Not necessary as we are checking on streams
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_ACCOUNTS_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'ACCOUNTS_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.ACCOUNTS',
    'SILVER.FINANCE.ACCOUNTS',
    'SILVER.UTILS.SP_ACCOUNTS_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- CASH_TRANSACTIONS
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_CASH_TRANSACTIONS_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
-- AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_CASH_TRANSACTIONS_LOAD -- Not necessary as we are checking on streams
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_CASHTRANSACTIONS_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'CASH_TRANSACTIONS_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.CASH_TRANSACTIONS',
    'SILVER.FINANCE.CASH_TRANSACTIONS',
    'SILVER.UTILS.SP_CASH_TRANSACTIONS_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- MARKET_PRICES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_MARKET_PRICES_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
-- AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_MARKET_PRICES_LOAD -- Not necessary as we are checking on streams
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_MARKETPRICES_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'MARKET_PRICES_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.MARKET_PRICES',
    'SILVER.FINANCE.MARKET_PRICES',
    'SILVER.UTILS.SP_MARKET_PRICES_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- SECURITIES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_SECURITIES_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
-- AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_SECURITIES_LOAD -- Not necessary as we are checking on streams
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_SECURITIES_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'SECURITIES_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.SECURITIES',
    'SILVER.FINANCE.SECURITIES',
    'SILVER.UTILS.SP_SECURITIES_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);


-- TRADES
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_TRADES_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
-- AFTER TASKS_DB.TASKS_SCHEMA.TASK_BRONZE_TRADES_LOAD -- Not necessary as we are checking on streams
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.FINANCE.BRONZE_TRADES_STREAM')
AS
CALL SILVER.UTILS.SP_GENERIC_SILVER_LOAD
(
    'TRADES_BRONZE_TO_SILVER',
    'SILVER',
    'BRONZE.FINANCE.TRADES',
    'SILVER.FINANCE.TRADES',
    'SILVER.UTILS.SP_TRADES_SILVER_TRANSFORMATIONS',
    'kgirija@defteam.co'
);

-- =========================================================
-- GOLD TASKS
-- =========================================================
CREATE OR REPLACE TASK TASKS_DB.TASKS_SCHEMA.TASK_GOLD_CONTROLLER_LOAD
WAREHOUSE = COMPUTE_WH
SCHEDULE = '5 MINUTE'
-- SCHEDULE = 'USING CRON 40 14 * * * Asia/Kolkata'
WHEN
    SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_Customers')
 OR SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_Accounts')
 OR SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_Securities')
 OR SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_Trades')
 OR SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_CashTransactions')
 OR SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_MarketPrices')
AS
CALL GOLD.UTILS.SP_GOLD_CONTROLLER_LOAD();

-- ================================
-- RESUME/SUSPEND TASKS
-- ================================

CALL TASKS_DB.TASKS_SCHEMA.SP_MANAGE_TASKS('RESUME');

CALL TASKS_DB.TASKS_SCHEMA.SP_MANAGE_TASKS('SUSPEND');