CREATE OR REPLACE PROCEDURE GOLD.UTILS.SP_GOLD_CONTROLLER_LOAD()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_CUSTOMER_CHANGED BOOLEAN;
    V_ACCOUNT_CHANGED BOOLEAN;
    V_SECURITY_CHANGED BOOLEAN;
    V_TRADE_CHANGED BOOLEAN;
    V_CASH_CHANGED BOOLEAN;
    V_PRICE_CHANGED BOOLEAN;
BEGIN

    V_CUSTOMER_CHANGED := SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_Customers');
    V_ACCOUNT_CHANGED  := SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_Accounts');
    V_SECURITY_CHANGED := SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_Securities');
    V_TRADE_CHANGED    := SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_Trades');
    V_CASH_CHANGED     := SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_CashTransactions');
    V_PRICE_CHANGED    := SYSTEM$STREAM_HAS_DATA('SILVER.FINANCE.STR_Silver_MarketPrices');

    -- 1. Load dimensions first
    IF (V_CUSTOMER_CHANGED) THEN
        CALL GOLD.UTILS.SP_LOAD_DIM_CUSTOMER();
    END IF;

    IF (V_ACCOUNT_CHANGED) THEN
        CALL GOLD.UTILS.SP_LOAD_DIM_ACCOUNT();
    END IF;

    IF (V_SECURITY_CHANGED) THEN
        CALL GOLD.UTILS.SP_LOAD_DIM_SECURITY();
    END IF;

    -- 2. Load facts after dimensions are available
    IF (V_CASH_CHANGED OR V_CUSTOMER_CHANGED OR V_ACCOUNT_CHANGED) THEN
        CALL GOLD.UTILS.SP_LOAD_FACT_CASH_TRANSACTION();
    END IF;

    IF (V_TRADE_CHANGED OR V_ACCOUNT_CHANGED OR V_CUSTOMER_CHANGED OR V_SECURITY_CHANGED) THEN
        CALL GOLD.UTILS.SP_LOAD_FACT_TRADE();
    END IF;

    IF (V_PRICE_CHANGED OR V_SECURITY_CHANGED) THEN
        CALL GOLD.UTILS.SP_LOAD_FACT_MARKET_PRICE();
    END IF;
    
    -- 3. Portfolio depends on facts/prices/security
    IF (V_PRICE_CHANGED OR V_TRADE_CHANGED OR V_SECURITY_CHANGED) THEN
        CALL GOLD.UTILS.SP_LOAD_FACT_PORTFOLIO_POSITION();
    END IF;

    RETURN 'GOLD LOAD COMPLETED';

END;
$$;