CREATE OR REPLACE PROCEDURE GOLD.UTILS.SP_LOAD_DIM_ACCOUNT()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE

    V_JOB_ID STRING DEFAULT UUID_STRING();
    V_JOB_NAME STRING DEFAULT 'LOAD_DIM_ACCOUNT';
	V_LAYER_NAME STRING DEFAULT 'GOLD';
    V_STATUS STRING;
    V_START_TIME TIMESTAMP;
    V_END_TIME TIMESTAMP;
    V_ROWS_PROCESSED NUMBER DEFAULT 0;
    V_ROWS_INSERTED NUMBER DEFAULT 0;
    V_ROWS_UPDATED NUMBER DEFAULT 0;
    V_ROWS_FAILED NUMBER DEFAULT 0;
    V_ERROR_MESSAGE STRING;

BEGIN

    -- START TIME
    V_START_TIME := CURRENT_TIMESTAMP();
	V_STATUS := 'STARTED';

    -- AUDIT START ENTRY
    INSERT INTO GOLD.FINANCE.AUDIT_JOB_LOG
    (
        JOB_ID,
        JOB_NAME,
        LAYER_NAME,
        SOURCE_OBJECT,
        TARGET_OBJECT,
        START_TIME,
        JOB_STATUS
    )
    VALUES
    (
        :V_JOB_ID,
        :V_JOB_NAME,
        :V_LAYER_NAME,
        'SILVER.FINANCE.ACCOUNTS',
        'GOLD.FINANCE.DIM_ACCOUNT',
        :V_START_TIME,
        :V_STATUS
    );

    -- SOURCE PREPARATION WITH NULL HANDLING
    CREATE OR REPLACE TEMP TABLE GOLD.FINANCE.TMP_ACCOUNTS AS
    SELECT
        COALESCE(ACCOUNT_ID, 'UNKNOWN') AS ACCOUNT_ID,
        COALESCE(CUSTOMER_ID, 'UNKNOWN') AS CUSTOMER_ID,
        COALESCE(ACCOUNT_NUMBER, 'UNKNOWN') AS ACCOUNT_NUMBER,
        COALESCE(ACCOUNT_TYPE, 'UNKNOWN') AS ACCOUNT_TYPE,
        COALESCE(ACCOUNT_STATUS, 'ACTIVE') AS ACCOUNT_STATUS,
        COALESCE(BASE_CURRENCY, 'USD') AS BASE_CURRENCY,
        OPENED_DATE,
        CLOSED_DATE,
        COALESCE(ADVISOR_CODE, 'NA') AS ADVISOR_CODE,
        MD5(
            CONCAT(
                COALESCE(ACCOUNT_ID, ''),
                '|',
                COALESCE(CUSTOMER_ID, ''),
                '|',
                COALESCE(ACCOUNT_NUMBER, ''),
                '|',
                COALESCE(ACCOUNT_STATUS, ''),
                '|',
                COALESCE(BASE_CURRENCY, '')
            )
        ) AS RECORD_HASH
    FROM SILVER.FINANCE.ACCOUNTS;

    -- ROWS PROCESSED
    SELECT COUNT(*) INTO :V_ROWS_PROCESSED FROM GOLD.FINANCE.TMP_ACCOUNTS;

    -- SCD TYPE 2 - EXPIRE OLD RECORDS
    UPDATE GOLD.FINANCE.DIM_ACCOUNT T
    SET
        EFFECTIVE_END_DATE = CURRENT_DATE - 1,
        IS_CURRENT = FALSE
    FROM GOLD.FINANCE.TMP_ACCOUNTS S
    WHERE T.ACCOUNT_ID = S.ACCOUNT_ID
      AND T.IS_CURRENT = TRUE
      AND T.RECORD_HASH <> S.RECORD_HASH;
	  
    V_ROWS_UPDATED := SQLROWCOUNT;

    -- INSERT NEW / CHANGED RECORDS
    INSERT INTO GOLD.FINANCE.DIM_ACCOUNT
    (
        ACCOUNT_ID,
        CUSTOMER_ID,
        ACCOUNT_NUMBER,
        ACCOUNT_TYPE,
        ACCOUNT_STATUS,
        BASE_CURRENCY,
        OPENED_DATE,
        CLOSED_DATE,
        ADVISOR_CODE,
        EFFECTIVE_START_DATE,
        EFFECTIVE_END_DATE,
        IS_CURRENT,
        RECORD_HASH
    )
    SELECT
        S.ACCOUNT_ID,
        S.CUSTOMER_ID,
        S.ACCOUNT_NUMBER,
        S.ACCOUNT_TYPE,
        S.ACCOUNT_STATUS,
        S.BASE_CURRENCY,
        S.OPENED_DATE,
        S.CLOSED_DATE,
        S.ADVISOR_CODE,
        CURRENT_DATE,
        null,
        TRUE,
        S.RECORD_HASH
    FROM GOLD.FINANCE.TMP_ACCOUNTS S
    LEFT JOIN GOLD.FINANCE.DIM_ACCOUNT T
           ON S.ACCOUNT_ID = T.ACCOUNT_ID
          AND T.IS_CURRENT = TRUE
    WHERE T.ACCOUNT_ID IS NULL
       OR T.RECORD_HASH <> S.RECORD_HASH;

    V_ROWS_INSERTED := SQLROWCOUNT;

    -- END TIME
    V_END_TIME := CURRENT_TIMESTAMP();
	V_STATUS := 'SUCCESS';

    -- AUDIT SUCCESS UPDATE
    UPDATE GOLD.FINANCE.AUDIT_JOB_LOG
    SET
        END_TIME = :V_END_TIME,
        ROWS_PROCESSED = :V_ROWS_PROCESSED,
        ROWS_INSERTED = :V_ROWS_INSERTED,
        ROWS_UPDATED = :V_ROWS_UPDATED,
        ROWS_FAILED = :V_ROWS_FAILED,
        JOB_STATUS = :V_STATUS
    WHERE JOB_ID = :V_JOB_ID;

    
    -- EMAIL NOTIFICATION  
    CALL SYSTEM$SEND_EMAIL(
        'finance_email_notification',
        'kgirija@defteam.co',
        'SUCCESS: ' || :V_JOB_NAME,
        'Job Name: ' || :V_JOB_NAME || '\n' ||
        'Job ID: ' || :V_JOB_ID || '\n' ||
        'Layer: ' || :V_LAYER_NAME || '\n' ||
        'Status: ' || :V_STATUS || '\n' ||
        'Rows Processed: ' || :V_ROWS_PROCESSED || '\n' ||
        'Rows Inserted: ' || :V_ROWS_INSERTED || '\n' ||
        'Rows Rejected: ' || :V_ROWS_FAILED || '\n' ||
        'Execution Time: ' || CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION

    WHEN OTHER THEN

        V_ERROR_MESSAGE := SQLERRM;
        V_END_TIME := CURRENT_TIMESTAMP();
        V_STATUS := 'FAILED';
		
        -- ALL REMAINING RECORDS CONSIDERED FAILED
        -- V_ROWS_FAILED := V_ROWS_PROCESSED - (V_ROWS_INSERTED + V_ROWS_UPDATED);

        -- AUDIT FAILURE UPDATE
        UPDATE GOLD.FINANCE.AUDIT_JOB_LOG
        SET
            END_TIME = :V_END_TIME,
            JOB_STATUS = :V_STATUS,
            ERROR_MESSAGE = :V_ERROR_MESSAGE
        WHERE JOB_ID = :V_JOB_ID;
        
        -- FAILURE EMAIL
        CALL SYSTEM$SEND_EMAIL(
            'finance_email_notification',
            'kgirija@defteam.co',
            'FAILED: ' || :V_JOB_NAME,
            'Job Name: ' || :V_JOB_NAME || '\n' ||
            'Job ID: ' || :V_JOB_ID || '\n' ||
            'Layer: ' || :V_LAYER_NAME || '\n' ||
            'Status: ' || :V_STATUS || '\n' ||
            'Execution Time: ' || CURRENT_TIMESTAMP() || '\n' ||
            'Error Message: ' || :V_ERROR_MESSAGE
        );

        RETURN 'FAILED: ' || :V_ERROR_MESSAGE;

END;
$$;