CREATE OR REPLACE PROCEDURE GOLD.UTILS.SP_LOAD_FACT_CASH_TRANSACTION()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE

    V_JOB_ID STRING DEFAULT UUID_STRING();
    V_JOB_NAME STRING DEFAULT 'SP_LOAD_FACT_CASH_TRANSACTION';
    V_LAYER_NAME STRING DEFAULT 'GOLD';
    V_STATUS STRING;
    V_START_TIME TIMESTAMP;
    V_END_TIME TIMESTAMP;
    V_ROWS_PROCESSED NUMBER DEFAULT 0;
    V_ROWS_INSERTED NUMBER DEFAULT 0;
    V_ROWS_UPDATED NUMBER DEFAULT 0;
    V_ROWS_FAILED NUMBER DEFAULT 0;
    V_ERROR_MESSAGE STRING;

BEGIN

    -- START TIME
    V_START_TIME := CURRENT_TIMESTAMP();
    V_STATUS := 'STARTED';

    -- AUDIT START ENTRY
    INSERT INTO GOLD.FINANCE.AUDIT_JOB_LOG
    (
        JOB_ID,
        JOB_NAME,
        LAYER_NAME,
        SOURCE_OBJECT,
        TARGET_OBJECT,
        START_TIME,
        JOB_STATUS
    )
    VALUES
    (
        :V_JOB_ID,
        :V_JOB_NAME,
        :V_LAYER_NAME,
        'SILVER.FINANCE.CASH_TRANSACTIONS',
        'GOLD.FINANCE.FACT_CASH_TRANSACTION',
        :V_START_TIME,
        :V_STATUS
    );

    -- DATA LOADING
    CREATE OR REPLACE TEMP TABLE GOLD.FINANCE.TMP_FACT_CASH_TRANSACTION AS
    SELECT
        COALESCE(T.CASH_TRANSACTION_ID, 'UNKNOWN') AS CASH_TRANSACTION_ID,
        COALESCE(DA.ACCOUNT_SK, -1) AS ACCOUNT_SK,
        COALESCE(DC.CUSTOMER_SK, -1) AS CUSTOMER_SK,
        CAST(T.TRANSACTION_DATE AS DATE) AS TRANSACTION_DATE,
        COALESCE(T.TRANSACTION_TYPE, 'UNKNOWN') AS TRANSACTION_TYPE,
        COALESCE(T.AMOUNT, 0) AS AMOUNT,
        COALESCE(T.FEE_AMOUNT, 0) AS FEE_AMOUNT,
        (COALESCE(T.AMOUNT, 0) - COALESCE(T.FEE_AMOUNT, 0)) AS NET_CASH_AMOUNT,
        
        -- SIGNED CASH FLOW
        CASE
            WHEN UPPER(T.TRANSACTION_TYPE) IN ('DEPOSIT', 'DIVIDEND', 'INTEREST')
            THEN COALESCE(T.AMOUNT, 0)

            WHEN UPPER(T.TRANSACTION_TYPE) IN ('WITHDRAWAL', 'FEE')
            THEN COALESCE(T.AMOUNT, 0) * -1

            ELSE 0

        END AS SIGNED_CASH_FLOW,

        -- OTHER FIELDS
        COALESCE(T.CURRENCY, 'USD') AS CURRENCY,
        COALESCE(T.TRANSACTION_STATUS, 'UNKNOWN') AS TRANSACTION_STATUS,
        CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

    FROM SILVER.FINANCE.CASH_TRANSACTIONS T

    LEFT JOIN GOLD.FINANCE.DIM_ACCOUNT DA
           ON T.ACCOUNT_ID = DA.ACCOUNT_ID
          AND DA.IS_CURRENT = TRUE

    LEFT JOIN GOLD.FINANCE.DIM_CUSTOMER DC
           ON DA.CUSTOMER_ID = DC.CUSTOMER_ID
          AND DC.IS_CURRENT = TRUE;

    -- ROWS PROCESSED
    SELECT COUNT(*) INTO :V_ROWS_PROCESSED FROM GOLD.FINANCE.TMP_FACT_CASH_TRANSACTION;

    -- INCREMENTAL LOAD: ONLY INSERT NEW CASH_TRANSACTION_ID
    INSERT INTO GOLD.FINANCE.FACT_CASH_TRANSACTION
    (
        CASH_TRANSACTION_ID,
        ACCOUNT_SK,
        CUSTOMER_SK,
        TRANSACTION_DATE,
        TRANSACTION_TYPE,
        AMOUNT,
        FEE_AMOUNT,
        NET_CASH_AMOUNT,
        SIGNED_CASH_FLOW,
        CURRENCY,
        TRANSACTION_STATUS,
        LOAD_TIMESTAMP
    )
    SELECT
        T.CASH_TRANSACTION_ID,
        T.ACCOUNT_SK,
        T.CUSTOMER_SK,
        T.TRANSACTION_DATE,
        T.TRANSACTION_TYPE,
        T.AMOUNT,
        T.FEE_AMOUNT,
        T.NET_CASH_AMOUNT,
        T.SIGNED_CASH_FLOW,
        T.CURRENCY,
        T.TRANSACTION_STATUS,
        T.LOAD_TIMESTAMP
    FROM GOLD.FINANCE.TMP_FACT_CASH_TRANSACTION T
    LEFT JOIN GOLD.FINANCE.FACT_CASH_TRANSACTION F
           ON T.CASH_TRANSACTION_ID = F.CASH_TRANSACTION_ID
    WHERE F.CASH_TRANSACTION_ID IS NULL;

    -- ROWS 
    V_ROWS_INSERTED := SQLROWCOUNT;

    -- END TIME
    V_END_TIME := CURRENT_TIMESTAMP();
    V_STATUS := 'SUCCESS';

    -- AUDIT SUCCESS UPDATE
    UPDATE GOLD.FINANCE.AUDIT_JOB_LOG
    SET
        END_TIME = :V_END_TIME,
        ROWS_PROCESSED = :V_ROWS_PROCESSED,
        ROWS_INSERTED = :V_ROWS_INSERTED,
        ROWS_UPDATED = :V_ROWS_UPDATED,
        ROWS_FAILED = :V_ROWS_FAILED,
        JOB_STATUS = :V_STATUS
    WHERE JOB_ID = :V_JOB_ID;

    -- SUCCESS EMAIL
    CALL SYSTEM$SEND_EMAIL(
        'finance_email_notification',
        'kgirija@defteam.co',
        'SUCCESS: ' || :V_JOB_NAME,
        'Job Name: ' || :V_JOB_NAME || '\n' ||
        'Job ID: ' || :V_JOB_ID || '\n' ||
        'Layer: ' || :V_LAYER_NAME || '\n' ||
        'Status: ' || :V_STATUS || '\n' ||
        'Rows Processed: ' || :V_ROWS_PROCESSED || '\n' ||
        'Rows Inserted: ' || :V_ROWS_INSERTED || '\n' ||
        'Rows Rejected: ' || :V_ROWS_FAILED || '\n' ||
        'Execution Time: ' || CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION

    WHEN OTHER THEN

        V_ERROR_MESSAGE := SQLERRM;
        V_END_TIME := CURRENT_TIMESTAMP();
        V_STATUS := 'FAILED';

        -- AUDIT FAILURE UPDATE
        UPDATE GOLD.FINANCE.AUDIT_JOB_LOG
        SET
            END_TIME = :V_END_TIME,
            JOB_STATUS = :V_STATUS,
            ERROR_MESSAGE = :V_ERROR_MESSAGE
        WHERE JOB_ID = :V_JOB_ID;

        -- FAILURE EMAIL
        CALL SYSTEM$SEND_EMAIL(
            'finance_email_notification',
            'kgirija@defteam.co',
            'FAILED: ' || :V_JOB_NAME,
            'Job Name: ' || :V_JOB_NAME || '\n' ||
            'Job ID: ' || :V_JOB_ID || '\n' ||
            'Layer: ' || :V_LAYER_NAME || '\n' ||
            'Status: ' || :V_STATUS || '\n' ||
            'Execution Time: ' || CURRENT_TIMESTAMP() || '\n' ||
            'Error Message: ' || :V_ERROR_MESSAGE
        );

        RETURN 'FAILED: ' || :V_ERROR_MESSAGE;

END;
$$;