CREATE OR REPLACE PROCEDURE GOLD.UTILS.SP_LOAD_FACT_MARKET_PRICE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE

    V_JOB_ID STRING DEFAULT UUID_STRING();
    V_JOB_NAME STRING DEFAULT 'SP_LOAD_FACT_MARKET_PRICE';
    V_LAYER_NAME STRING DEFAULT 'GOLD';
    V_STATUS STRING;
    V_START_TIME TIMESTAMP;
    V_END_TIME TIMESTAMP;
    V_ROWS_PROCESSED NUMBER DEFAULT 0;
    V_ROWS_INSERTED NUMBER DEFAULT 0;
    V_ROWS_UPDATED NUMBER DEFAULT 0;
    V_ROWS_FAILED NUMBER DEFAULT 0;
    V_ERROR_MESSAGE STRING;

BEGIN

    -- START TIME
    V_START_TIME := CURRENT_TIMESTAMP();
    V_STATUS := 'STARTED';
    
    -- AUDIT START ENTRY
    INSERT INTO GOLD.FINANCE.AUDIT_JOB_LOG
    (
        JOB_ID,
        JOB_NAME,
        LAYER_NAME,
        SOURCE_OBJECT,
        TARGET_OBJECT,
        START_TIME,
        JOB_STATUS
    )
    VALUES
    (
        :V_JOB_ID,
        :V_JOB_NAME,
        :V_LAYER_NAME,
        'SILVER.FINANCE.MARKET_PRICES',
        'GOLD.FINANCE.FACT_MARKET_PRICE',
        :V_START_TIME,
        :V_STATUS
    );

    -- NULL HANDLING
    CREATE OR REPLACE TEMP TABLE GOLD.FINANCE.TMP_FACT_MARKET_PRICE AS
    SELECT
        MP.PRICE_ID,
        COALESCE(DS.SECURITY_SK, -1) AS SECURITY_SK,
		CAST(MP.PRICE_DATE AS DATE) AS PRICE_DATE,
		COALESCE(MP.OPEN_PRICE, 0) AS OPEN_PRICE,
		COALESCE(MP.HIGH_PRICE, 0) AS HIGH_PRICE,
		COALESCE(MP.LOW_PRICE, 0) AS LOW_PRICE,
		COALESCE(MP.CLOSE_PRICE, 0) AS CLOSE_PRICE,
		COALESCE(MP.ADJUSTED_CLOSE_PRICE, 0) AS ADJUSTED_CLOSE_PRICE,
		COALESCE(MP.PRICE_CURRENCY, 'USD') AS PRICE_CURRENCY,
		COALESCE(MP.FX_RATE_TO_BASE, 0) AS FX_RATE_TO_BASE,
        CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
    FROM SILVER.FINANCE.MARKET_PRICES MP

    LEFT JOIN GOLD.FINANCE.DIM_SECURITY DS
           ON MP.SECURITY_ID = DS.SECURITY_ID
          AND DS.IS_CURRENT = TRUE;
          
    -- ROWS PROCESSED
    SELECT COUNT(*) INTO :V_ROWS_PROCESSED FROM GOLD.FINANCE.TMP_FACT_MARKET_PRICE;

    -- INSERT INTO FACT TABLE
    INSERT INTO GOLD.FINANCE.FACT_MARKET_PRICE
    (
        PRICE_ID,
		SECURITY_SK,
		PRICE_DATE,
		OPEN_PRICE,
		HIGH_PRICE,
		LOW_PRICE,
		CLOSE_PRICE,
		ADJUSTED_CLOSE_PRICE,
		PRICE_CURRENCY,
		FX_RATE_TO_BASE,
		LOAD_TIMESTAMP
    )
    SELECT
        TMP.PRICE_ID,
		TMP.SECURITY_SK,
		TMP.PRICE_DATE,
		TMP.OPEN_PRICE,
		TMP.HIGH_PRICE,
		TMP.LOW_PRICE,
		TMP.CLOSE_PRICE,
		TMP.ADJUSTED_CLOSE_PRICE,
		TMP.PRICE_CURRENCY,
		TMP.FX_RATE_TO_BASE,
		TMP.LOAD_TIMESTAMP
    FROM GOLD.FINANCE.TMP_FACT_MARKET_PRICE TMP
    LEFT JOIN GOLD.FINANCE.FACT_MARKET_PRICE F
           ON TMP.PRICE_ID = F.PRICE_ID
    WHERE F.PRICE_ID IS NULL;

    V_ROWS_INSERTED := SQLROWCOUNT;

    -- END TIME
    V_END_TIME := CURRENT_TIMESTAMP();
    V_STATUS := 'SUCCESS';
    
    -- AUDIT SUCCESS UPDATE
    UPDATE GOLD.FINANCE.AUDIT_JOB_LOG
    SET
        END_TIME = :V_END_TIME,
        ROWS_PROCESSED = :V_ROWS_PROCESSED,
        ROWS_INSERTED = :V_ROWS_INSERTED,
        ROWS_FAILED = :V_ROWS_FAILED,
        JOB_STATUS = :V_STATUS
    WHERE JOB_ID = :V_JOB_ID;

    -- SUCCESS EMAIL NOTIFICATION
    CALL SYSTEM$SEND_EMAIL(
        'finance_email_notification',
        'kgirija@defteam.co',
        'SUCCESS: ' || :V_JOB_NAME,
        'Job Name: ' || :V_JOB_NAME || '\n' ||
        'Job ID: ' || :V_JOB_ID || '\n' ||
        'Layer: ' || :V_LAYER_NAME || '\n' ||
        'Status: ' || :V_STATUS || '\n' ||
        'Rows Processed: ' || :V_ROWS_PROCESSED || '\n' ||
        'Rows Inserted: ' || :V_ROWS_INSERTED || '\n' ||
        'Rows Rejected: ' || :V_ROWS_FAILED || '\n' ||
        'Execution Time: ' || CURRENT_TIMESTAMP()
    );

    CREATE TEMPORARY TABLE GOLD.FINANCE.Tmp_Str_Silver_MarketPrices AS SELECT * FROM SILVER.FINANCE.STR_Silver_MarketPrices WHERE 1=0;
    
    RETURN 'SUCCESS';

EXCEPTION

    WHEN OTHER THEN

        V_ERROR_MESSAGE := SQLERRM;
        V_END_TIME := CURRENT_TIMESTAMP();
        V_STATUS := 'FAILED';

        -- AUDIT FAILURE UPDATE
        UPDATE GOLD.FINANCE.AUDIT_JOB_LOG
        SET
            END_TIME = :V_END_TIME,
            JOB_STATUS = :V_STATUS,
            ERROR_MESSAGE = :V_ERROR_MESSAGE
        WHERE JOB_ID = :V_JOB_ID;

        -- FAILURE EMAIL NOTIFICATION
        CALL SYSTEM$SEND_EMAIL(
            'finance_email_notification',
            'kgirija@defteam.co',
            'FAILED: ' || :V_JOB_NAME,
            'Job Name: ' || :V_JOB_NAME || '\n' ||
            'Job ID: ' || :V_JOB_ID || '\n' ||
            'Layer: ' || :V_LAYER_NAME || '\n' ||
            'Status: ' || :V_STATUS || '\n' ||
            'Execution Time: ' || CURRENT_TIMESTAMP() || '\n' ||
            'Error Message: ' || :V_ERROR_MESSAGE
        );

        RETURN 'FAILED: ' || :V_ERROR_MESSAGE;

END;
$$;