CREATE OR REPLACE PROCEDURE BRONZE.UTILS.SP_PROCESS_STAGE_FILES()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    v_folder STRING;
    c_folders CURSOR FOR
        SELECT DISTINCT SPLIT_PART(RELATIVE_PATH,'/',1) AS FOLDER_NAME
        FROM BRONZE.FINANCE.STR_BRONZE_STAGE
        WHERE METADATA$ACTION = 'INSERT';
    
BEGIN

    FOR rec IN c_folders DO

        v_folder := UPPER(rec.FOLDER_NAME);

        CASE v_folder

            WHEN 'CUSTOMERS' THEN
                CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('CUSTOMERS');

            WHEN 'ACCOUNTS' THEN
                CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('ACCOUNTS');

            WHEN 'SECURITIES' THEN
                CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('SECURITIES');

            WHEN 'TRADES' THEN
                CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('TRADES');

            WHEN 'MARKETPRICES' THEN
                CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('MARKET_PRICES');

            WHEN 'CASHTRANSACTIONS' THEN
                CALL BRONZE.UTILS.SP_GENERIC_BRONZE_LOAD('CASH_TRANSACTIONS');

        END CASE;
    END FOR;

    RETURN 'SUCCESS';

END;
$$;